dist: xenial
language: node_js
sudo: false
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "6"
env:
  - KARMA_VERSION=1.3
  - KARMA_VERSION=1.4
  - KARMA_VERSION=1.5
  - KARMA_VERSION=1.6
  - KARMA_VERSION=1.7
  - KARMA_VERSION=2.0
  - KARMA_VERSION=3.0
  - KARMA_VERSION=3.1
  - KARMA_VERSION=4.4
  - KARMA_VERSION=5.2
addons:
  chrome: stable
before_install:
  - npm install --save-dev karma@"$KARMA_VERSION"
before_script:
  - export CHROME_BIN=chromium-browser
  - export KARMA_BROWSER=Firefox,Chrome_NoSandbox
services:
  - xvfb
