name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        karma-version: [2.0.x, 3.0.x, 3.1.x, 4.4.x, 5.x, 6.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm install --save-dev karma@${{ matrix.karma-version }}
      - run: npm run test

